name: Frontend CI/CD

on:
  push:
    branches:
      - main

env:
  VITE_API_URL: ${{ secrets.VITE_API_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Run tests
        run: |
          cd client
          npm run test || echo "No tests found"

      - name: Build frontend
        run: |
          cd client
          npm run build

      - name: Trigger Vercel Deploy
        run: echo "Vercel auto-deploys when GitHub repo is updated. No SSH needed."
