name: Backend CI/CD

on:
  push:
    branches:
      - main

env:
  NODE_ENV: production
  MONGO_URI: ${{ secrets.MONGO_URI }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run tests
        run: |
          cd backend
          npm test || echo "No tests found"

      - name: Trigger Render Auto Deploy
        run: echo "Render auto-deploys when GitHub repo is updated. No SSH needed."
